<a href="https://colab.research.google.com/github/SOUJU07/DSMP-Notebooks/blob/main/Copy_of_Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [5]:
#Code here
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [11]:
#Code here

a=int(input('enter first number'))
b=int(input('enter second number'))

x=np.random.rand(a,b)
print(x)

enter first number2
enter second number4
[[0.78441362 0.69813094 0.97116423 0.3282718 ]
 [0.06080499 0.07452573 0.3496591  0.0533457 ]]


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [25]:
#Code here

def arr(a,b):
  c=np.ones((a,b),dtype=int)
  c[1:3,1:3]=0
  return c

x=arr(4,4)
print(x)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [32]:
#Code here
a=np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [38]:
#Code here
x=np.eye(3,4)
print(x)  # yes we can create using eye method, also this 2d matrix try to provide 1 at diagonals.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [44]:
#Code here
np.arange(5).reshape(1,5).repeat(5,axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [65]:
#code here
a=np.random.randint(1,101,size=(10,2))
print('random points',a)

given_point = np.array([2,3])
print('given_point',given_point)

distance=np.sqrt(np.sum((a-given_point)**2,axis=1)).astype(int)
print(distance)

random points [[ 41 100]
 [ 93  28]
 [ 45  98]
 [ 59  18]
 [ 66  78]
 [ 69  59]
 [ 49  24]
 [ 50  83]
 [ 37  26]
 [ 43  35]]
given_point [2 3]
[104  94 104  58  98  87  51  93  41  52]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
#Code here

np.unravel_index(100, (6, 7, 8))


(np.int64(1), np.int64(5), np.int64(4))

In [75]:
tuple(int(i) for i in np.unravel_index(100, (6, 7, 8)))


(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [93]:
#Code here

a=input().strip().split()
np.array(a[::-1],dtype=np.float32)

2 3 4


array([4., 3., 2.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [100]:
#Code here
a=np.array([1, 2,3,4,2])
elements_count = 0
for i in np.nditer(a):
  elements_count+=1

print(elements_count)


5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [102]:
#Code here

def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

x=np.array([33.17344305,45.61961654,82.05405781,80.9647098,68.82830233,91.52064278])
softmax(x)


array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [140]:
def vertical_stack(*args):
  for i in args:
    if type(i)!=np.ndarray:
      raise TypeError('invalid, give a numpy array only')
  return np.vstack(args)


a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
c=np.array([1,2,3,4,5])
x=vertical_stack(a,b,c)
print(type(a))
print(a)
print(b)
print(x)


<class 'numpy.ndarray'>
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 2 3 4 5]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [31]:
#Code here
import numpy as np
from datetime import datetime,timedelta
def date_array(start_date,end_date):
  if type(start_date)!=str or type(end_date)!=str:
    raise TypeError('give dates as strings only')
  else:
    srt=datetime.strptime(start_date,'%Y-%m-%d')
    end=datetime.strptime(end_date,'%Y-%m-%d')
    days=(end-srt).days

    dates=[]
    for i in range(days+1):
      x=srt+timedelta(days=i)
      dates.append(x)
    return np.array([datetime.strftime(d,'%Y-%m-%d') for d in dates])
start_date='2020-11-25'
end_date='2020-11-30'

x=date_array(start_date,end_date)
print(x)

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [38]:
#code here

a=np.arange(4).reshape(2,2)
print(a)
x=a.mean(axis=1,keepdims=True)
y=a-x
y

[[0 1]
 [2 3]]


array([[-0.5,  0.5],
       [-0.5,  0.5]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [53]:
#Code here
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [56]:
A[:,[0,2,1]]
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###`Q-16:` Replace odd elements in arrays with -1.

In [57]:
#Code here
import numpy as np

A = np.array([1, 2, 3, 4, 5, 6])
A[A%2==1]=-1
A

array([-1,  2, -1,  4, -1,  6])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [58]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=np.maximum(a,b)
print(c)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [62]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3930,  496, 7558, 2040, 9845],
       [5747, 9389, 3933, 8222, 2862],
       [9663, 4819,  904, 4272, 3970],
       [8967, 5627,   55, 9181, 3568],
       [5234,  271, 5858, 9170, 8072],
       [7385, 6758, 1378, 6874, 1820],
       [1025, 3031, 2396, 8704, 4590],
       [4478, 7998, 9256, 6458, 9767]])

In [63]:
#Code here
arr1[:, ::2]

array([[3930, 7558, 9845],
       [5747, 3933, 2862],
       [9663,  904, 3970],
       [8967,   55, 3568],
       [5234, 5858, 8072],
       [7385, 1378, 1820],
       [1025, 2396, 4590],
       [4478, 9256, 9767]])

In [64]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.39581205, 0.04504597, 0.76639428, 0.20275792, 1.        ],
       [0.5814096 , 0.95342186, 0.39611849, 0.83421859, 0.28672114],
       [0.9814096 , 0.486619  , 0.08672114, 0.43074566, 0.39989785],
       [0.91031665, 0.5691522 , 0.        , 0.93217569, 0.35883555],
       [0.52900919, 0.02206333, 0.5927477 , 0.93105209, 0.81889683],
       [0.74872319, 0.68467824, 0.1351379 , 0.69652707, 0.18028601],
       [0.09908069, 0.30398366, 0.23912155, 0.8834525 , 0.46322778],
       [0.45178754, 0.8113381 , 0.93983657, 0.65403473, 0.99203269]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [65]:

#Code here
def nthmax(arr, n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

np.int64(34)

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [61]:
import numpy as np

a = np.array([1, 2, 3])

result = np.concatenate((np.repeat(a, len(a)),
                          np.tile(a, len(a))))

print(result)


[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
